export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const SET_SEARCH_ENGINE = 'SET_SEARCH_ENGINE';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GOOGLE_SE = 'Google';
export const BING_SE = 'Bing';
export const SET_PAGINATION_OFFSET = 'SET_PAGINATION_OFFSET';
export const CLEAR_PAGINATION_OFFSET = 'CLEAR_PAGINATION_OFFSET';